-- Top 10 Suppliers
SELECT
SUPPLIER,
ROUND(SUM(`RETAIL SALES`),2) AS TotalSales
FROM retail_sales
GROUP BY SUPPLIER
ORDER BY TotalSales DESC
LIMIT 10;

-- Monthly Sales
SELECT
YEAR,
MONTH,
ROUND(SUM(`RETAIL SALES`),2) AS Sales
FROM retail_sales
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH;

-- Top Products
SELECT
`ITEM DESCRIPTION`,
ROUND(SUM(`RETAIL SALES`),2) AS Sales
FROM retail_sales
GROUP BY `ITEM DESCRIPTION`
ORDER BY Sales DESC
LIMIT 10;

-- Top Categories
SELECT
`ITEM TYPE`,
ROUND(SUM(`RETAIL SALES`),2) AS Sales
FROM retail_sales
GROUP BY `ITEM TYPE`
ORDER BY Sales DESC;